require_relative "iocheck"

tester = IOCheck::Tester.new

tester << IOCheck::Test.new("tree")
tester << IOCheck::Test.new("main").repeat(10).name("prod of 1 to 10").describe("multiply 1 to 10")

tester.ready
